### ISSUE TITLE
Only relative path support ?

### ISSUE THREAD

**Issue by drumicube** [Billius-AI/ComfyUI-Path-Helper#1]
Hello, and thanks for your helper project.

In my current workflow, I save frames generated by AnimateDiff. It's then possible to activate an optional group on a later run to reload the last generated png for a hires-fix upscaling.
I'm using those nodes for saving and reloading:

![Screenshot from 2024-02-12 22-38-05](https://github.com/Billius-AI/ComfyUI-Path-Helper/assets/123496712/cf0499ac-a7b0-4fdc-acda-a4f43574e50a)

It's quite possible to use relative path for those nodes, but sadly they're not referencing the same root.
If I remember correctly, one is using /home/user/ComfyUi and the other /home/user/ComfyUi/output as references.

As you can imagine this can lead to a complex situation in no time, so I switched to absolute path to unify inputs.
Does your extension support Absolute path, from what I saw I only managed to get relative ones.

Thanks.

**Comment by Billius-AI** [comment]
Hey @drumicube so I just created a branch "create-project-absolute-path" with a quick update to Create project root Node so it now has a toggle for if the path generation is relative or absolute. Did a quick bit of testing and seems to work correctly. In both cases its still defaulting to the output dir though. Does that solve your issue or would you like to be able to set the project at the ComfyUI repo root itself? 

https://github.com/Billius-AI/ComfyUI-Path-Helper/tree/create-project-absolute-path
